apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 51.77.213.65
spec:
  type: LoadBalancer
  selector:
    name: couchdb
  ports:
    - name: "5984"
      port: 5984
      targetPort: 5984
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: default
data:
  docker.ini: |
    [couchdb]
    single_node=true
    max_document_size = 50000000

    [chttpd]
    require_valid_user = true
    max_http_request_size = 4294967296
    enable_cors = true

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    bind_address = 0.0.0.0

    [cors]
    origins = app://obsidian.md, capacitor://localhost, http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET,PUT,POST,HEAD,DELETE
    max_age = 3600
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: couchdb
  template:
    metadata:
      labels:
        name: couchdb
        namespace: default
    spec:
      containers:
        - name: couchdb
          image: couchdb:3.3.2
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: env
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: COUCHDB_PASSWORD
          ports:
            - containerPort: 5984
              hostPort: 5984
              protocol: TCP
          volumeMounts:
            - name: couchdb-pvc
              mountPath: /opt/couchdb/data
            - name: tmp-config
              mountPath: /opt/couchdb/etc/local.d/
      initContainers:
        - name: copy
          image: busybox:1.36.1
          command:
            - "/bin/sh"
            - "-c"
            - "cp /config/docker.ini /opt/couchdb/etc/local.d/"
          volumeMounts:
            - name: tmp-config
              mountPath: /opt/couchdb/etc/local.d/
            - name: couchdb-config
              mountPath: /config/
      restartPolicy: Always
      volumes:
        - name: couchdb-pvc
          persistentVolumeClaim:
            claimName: couchdb-pvc
        - name: couchdb-config
          configMap:
            name: couchdb-config
            items:
              - key: docker.ini
                path: docker.ini
        - name: tmp-config
          emptyDir: {}
