apiVersion: v1
kind: Namespace
metadata:
  name: couchdb
  labels:
    name: couchdb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: couchdb-ingress
  namespace: couchdb
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - couchdb.stephenmwangi.com
      secretName: lets-encrypt-private-key
  rules:
    - host: couchdb.stephenmwangi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: couchdb-svc
                port:
                  number: 5984
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-svc
  namespace: couchdb
spec:
  type: ClusterIP
  selector:
    name: couchdb
  ports:
    - name: "5984"
      port: 5984
      targetPort: 5984
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
  namespace: couchdb
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: couchdb
data:
  docker.ini: |
    [couchdb]
    single_node = true
    max_document_size = 50000000
    uuid = 1f090445d8acf2df2893959fd582767c

    [chttpd]
    require_valid_user = true
    max_http_request_size = 4294967296

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    bind_address = 0.0.0.0
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET,PUT,POST,HEAD,DELETE
    max_age = 3600
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: couchdb
spec:
  selector:
    matchLabels:
      name: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb
        namespace: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb:3.3.3
          imagePullPolicy: IfNotPresent
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: env
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: COUCHDB_PASSWORD
          ports:
            - containerPort: 5984
              protocol: TCP
          volumeMounts:
            - name: couchdb-pvc
              mountPath: /opt/couchdb/data
            - name: tmp-config
              mountPath: /opt/couchdb/etc/local.d/
      initContainers:
        - name: copy
          image: busybox:1.36.1
          command:
            - "/bin/sh"
            - "-c"
            - "cp /config/docker.ini /opt/couchdb/etc/local.d/"
          volumeMounts:
            - name: tmp-config
              mountPath: /opt/couchdb/etc/local.d/
            - name: couchdb-config
              mountPath: /config/
      restartPolicy: Always
      volumes:
        - name: couchdb-pvc
          persistentVolumeClaim:
            claimName: couchdb-pvc
        - name: couchdb-config
          configMap:
            name: couchdb-config
            items:
              - key: docker.ini
                path: docker.ini
        - name: tmp-config
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - mars
