apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: mail@stephenmwangi.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-private-key
    solvers:
      - http01:
          ingress:
            class: public
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - infra.stephenmwangi.com
      secretName: infra-svc-ingress-tls
  rules:
    - host: infra.stephenmwangi.com
      http:
        paths:
          - backend:
              service:
                name: couchdb-svc
                port:
                  number: 5984
            path: /couchdb(/|$)(.*)
            pathType: Prefix
