apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
  namespace: ingress
spec:
  acme:
    email: mail@stephenmwangi.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-private-key
    solvers:
      - http01:
          ingress:
            class: public
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cauldron
  namespace: ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - cauldron.stephenmwangi.com
      secretName: infra-svc-ingress-tls
  rules: []
