apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: redis
spec:
  type: ClusterIP
  selector:
    name: redis
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      name: redis
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
        namespace: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          imagePullPolicy: IfNotPresent
          args:
            - "--save"
            - "900"
            - "1"
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - mars
